// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRNsA_EnuTLSZOP2ih_JdL95zNWewi6Hk',
    appId: '1:908995759075:web:89bb106bf4ffaf07712ed6',
    messagingSenderId: '908995759075',
    projectId: 'coin-compass-eaadb',
    authDomain: 'coin-compass-eaadb.firebaseapp.com',
    storageBucket: 'coin-compass-eaadb.appspot.com',
    measurementId: 'G-QY29VRVHVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjUElsWKf7OAheMhvdftLLrLMC-iaFcjM',
    appId: '1:908995759075:android:d1bf1e3420639e90712ed6',
    messagingSenderId: '908995759075',
    projectId: 'coin-compass-eaadb',
    storageBucket: 'coin-compass-eaadb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZX6k_BAg6PrLHI2oUZCRt9zcO2P8sno0',
    appId: '1:908995759075:ios:5dc88578583b26b2712ed6',
    messagingSenderId: '908995759075',
    projectId: 'coin-compass-eaadb',
    storageBucket: 'coin-compass-eaadb.appspot.com',
    iosBundleId: 'com.example.coinCompass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZX6k_BAg6PrLHI2oUZCRt9zcO2P8sno0',
    appId: '1:908995759075:ios:a779d330323fb571712ed6',
    messagingSenderId: '908995759075',
    projectId: 'coin-compass-eaadb',
    storageBucket: 'coin-compass-eaadb.appspot.com',
    iosBundleId: 'com.example.coinCompass.RunnerTests',
  );
}
